#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

DEST="$(mktemp --directory)"

jekyll build --source=jekyll-site --destination="${DEST}"
cp -r apps "${DEST}"
cp CNAME "${DEST}"

git submodule update --init

(
    cd seam-carving-js
    npm install
    PROD=1 gulp build
    cp -r dist "${DEST}/seam-carving"
    git checkout .
)

rm --force --recursive docs
mv ${DEST} docs
