#!/bin/bash

# Rebuilds the seam-carving app from the seam-carving-js submodule and
# copies the result into docs/. The rest of the site is plain HTML that
# lives directly in docs/ and needs no build step.

set -o errexit
set -o nounset
set -o xtrace

git submodule update --init --remote

(
    cd seam-carving-js
    npm install
    PROD=1 gulp build
    git checkout .
)

rm -rf docs/seam-carving
cp -r seam-carving-js/dist docs/seam-carving
